In [1]:
from pymongo import MongoClient
import pandas as pd

In [2]:
mongo_uri = "mongodb://localhost:27017/"
db_name = "SpotifyAnalytics"
collection_name = "tracks"

In [3]:
client = MongoClient(mongo_uri)
db = client[db_name]
collection = db[collection_name]

In [4]:
df = pd.read_csv('/Users/alfiyaansari/Desktop/Important/Project/spotify_2015_2025_85k.csv')
df.head()

,track_id,track_name,artist_name,album_name,release_date,genre,duration_ms,popularity,danceability,energy,key,loudness,mode,instrumentalness,tempo,stream_count,country,explicit,label
0,TRK-BEBD53DA84E1,Agent every (0),Noah Rhodes,Beautiful instead,2016-04-01,Pop,234194,55,0.15,0.74,9,-32.22,0,0.436,73.12,13000,Brazil,0,Universal Music
1,TRK-6A32496762D7,Night respond,Jennifer Cole,Table,2022-04-15,Metal,375706,45,0.44,0.46,0,-14.02,0,0.223,157.74,1000,France,1,Island Records
2,TRK-47AA7523463E,Future choice whatever,Brandon Davis,Page southern,2016-02-23,Rock,289191,55,0.62,0.80,8,-48.26,1,0.584,71.03,1000,Germany,1,XL Recordings
3,TRK-25ADA22E3B06,Bad fall pick those,Corey Jones,Spring,2015-10-12,Pop,209484,51,0.78,0.98,1,-34.47,1,0.684,149.00,1000,France,0,Warner Music
4,TRK-9245F2AD996A,Husband,Mark Diaz,Great prove,2022-07-08,Indie,127435,39,0.74,0.18,10,-17.84,0,0.304,155.85,2000,United States,0,Independent

In [5]:
df['duration_ms'] = round(df['duration_ms'] / 60000)
df.rename(columns={"duration_ms" : "duration_minutes"},inplace=True)

In [6]:
df.head()

,track_id,track_name,artist_name,album_name,release_date,genre,duration_minutes,popularity,danceability,energy,key,loudness,mode,instrumentalness,tempo,stream_count,country,explicit,label
0,TRK-BEBD53DA84E1,Agent every (0),Noah Rhodes,Beautiful instead,2016-04-01,Pop,4.0,55,0.15,0.74,9,-32.22,0,0.436,73.12,13000,Brazil,0,Universal Music
1,TRK-6A32496762D7,Night respond,Jennifer Cole,Table,2022-04-15,Metal,6.0,45,0.44,0.46,0,-14.02,0,0.223,157.74,1000,France,1,Island Records
2,TRK-47AA7523463E,Future choice whatever,Brandon Davis,Page southern,2016-02-23,Rock,5.0,55,0.62,0.80,8,-48.26,1,0.584,71.03,1000,Germany,1,XL Recordings
3,TRK-25ADA22E3B06,Bad fall pick those,Corey Jones,Spring,2015-10-12,Pop,3.0,51,0.78,0.98,1,-34.47,1,0.684,149.00,1000,France,0,Warner Music
4,TRK-9245F2AD996A,Husband,Mark Diaz,Great prove,2022-07-08,Indie,2.0,39,0.74,0.18,10,-17.84,0,0.304,155.85,2000,United States,0,Independent

In [8]:
df['release_date'] = pd.to_datetime(df['release_date'], errors = 'coerce')
df['release_year'] = df['release_date'].dt.year

In [11]:
def pop_level(x):
    if x >= 70:
        return 'High'
    elif x >= 40:
        return 'Medium'
    else:
        return 'Low'

In [12]:
df['popularity_level'] = df['popularity'].apply(pop_level)

In [13]:
df.head()

,track_id,track_name,artist_name,album_name,release_date,genre,duration_minutes,popularity,danceability,energy,...,loudness,mode,instrumentalness,tempo,stream_count,country,explicit,label,release_year,popularity_level
0,TRK-BEBD53DA84E1,Agent every (0),Noah Rhodes,Beautiful instead,2016-04-01,Pop,4.0,55,0.15,0.74,...,-32.22,0,0.436,73.12,13000,Brazil,0,Universal Music,2016,Medium
1,TRK-6A32496762D7,Night respond,Jennifer Cole,Table,2022-04-15,Metal,6.0,45,0.44,0.46,...,-14.02,0,0.223,157.74,1000,France,1,Island Records,2022,Medium
2,TRK-47AA7523463E,Future choice whatever,Brandon Davis,Page southern,2016-02-23,Rock,5.0,55,0.62,0.80,...,-48.26,1,0.584,71.03,1000,Germany,1,XL Recordings,2016,Medium
3,TRK-25ADA22E3B06,Bad fall pick those,Corey Jones,Spring,2015-10-12,Pop,3.0,51,0.78,0.98,...,-34.47,1,0.684,149.00,1000,France,0,Warner Music,2015,Medium
4,TRK-9245F2AD996A,Husband,Mark Diaz,Great prove,2022-07-08,Indie,2.0,39,0.74,0.18,...,-17.84,0,0.304,155.85,2000,United States,0,Independent,2022,Low

In [15]:
pd.set_option('display.max_columns',50)

In [16]:
df.head()

,track_id,track_name,artist_name,album_name,release_date,genre,duration_minutes,popularity,danceability,energy,key,loudness,mode,instrumentalness,tempo,stream_count,country,explicit,label,release_year,popularity_level
0,TRK-BEBD53DA84E1,Agent every (0),Noah Rhodes,Beautiful instead,2016-04-01,Pop,4.0,55,0.15,0.74,9,-32.22,0,0.436,73.12,13000,Brazil,0,Universal Music,2016,Medium
1,TRK-6A32496762D7,Night respond,Jennifer Cole,Table,2022-04-15,Metal,6.0,45,0.44,0.46,0,-14.02,0,0.223,157.74,1000,France,1,Island Records,2022,Medium
2,TRK-47AA7523463E,Future choice whatever,Brandon Davis,Page southern,2016-02-23,Rock,5.0,55,0.62,0.80,8,-48.26,1,0.584,71.03,1000,Germany,1,XL Recordings,2016,Medium
3,TRK-25ADA22E3B06,Bad fall pick those,Corey Jones,Spring,2015-10-12,Pop,3.0,51,0.78,0.98,1,-34.47,1,0.684,149.00,1000,France,0,Warner Music,2015,Medium
4,TRK-9245F2AD996A,Husband,Mark Diaz,Great prove,2022-07-08,Indie,2.0,39,0.74,0.18,10,-17.84,0,0.304,155.85,2000,United States,0,Independent,2022,Low

In [22]:
records = df.to_dict(orient='records')

In [23]:
collection.insert_many(records)
print(f'Inserted {len(records)} spotify track documents')

Inserted 85000 spotify track documents

In [ ]:
§§