In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
%load_ext sql
%sql mysql+pymysql://root:admin1234@localhost/netflix

In [3]:
df = pd.read_csv('/Users/alfiyaansari/Desktop/Project/netflix_titles.csv')
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [4]:
df.shape

(8807, 12)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [6]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [7]:
df['director'] = df['director'].fillna('Unknown')
df['cast'] = df['cast'].fillna('Unknown')
df['country']=df['country'].fillna('Unknown')

In [8]:
df.dropna(axis=0,inplace=True)

In [9]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [10]:
for col in df.columns:
    print(f"Value counts for column '{col}':")
    print(df[col].value_counts())
    print('-' * 40)

Value counts for column 'show_id':
show_id
s1       1
s5867    1
s5861    1
s5862    1
s5863    1
        ..
s2924    1
s2923    1
s2922    1
s2921    1
s8807    1
Name: count, Length: 8790, dtype: int64
----------------------------------------
Value counts for column 'type':
type
Movie      6126
TV Show    2664
Name: count, dtype: int64
----------------------------------------
Value counts for column 'title':
title
Dick Johnson Is Dead                1
Cooked                              1
My Beautiful Broken Brain           1
Pee-wee's Big Holiday               1
Netflix Presents: The Characters    1
                                   ..
Sleepless Society: Insomnia         1
Palazuelos mi rey                   1
Narcos: Mexico                      1
Love Is Blind                       1
Zubaan                              1
Name: count, Length: 8790, dtype: int64
----------------------------------------
Value counts for column 'director':
director
Unknown                           2621
Rajiv Chilaka                       19
Raúl Campos, Jan Suter              18
Suhas Kadav                         16
Marcus Raboy                        16
                                  ...
Raymie Muzquiz, Stu Livingston       1
Joe Menendez                         1
Eric Bross                           1
Will Eisenberg                       1
Mozez Singh                          1
Name: count, Length: 4527, dtype: int64
----------------------------------------
Value counts for column 'cast':
cast
Unknown                                                                                                                                          825
David Attenborough                                                                                                                                19
Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jigna Bhardwaj, Rajesh Kava, Mousam, Swapnil                                                           14
Samuel West                                                                                                                                       10
Jeff Dunham                                                                                                                                        7
                                                                                                                                                ...
Sanjay Dutt, Arjun Kapoor, Kriti Sanon, Zeenat Aman, Mohnish Bahl, Padmini Kolhapure, Kunal Kapoor, Suhasini Mulay                                 1
Lika Berning, Bobby van Jaarsveld, Marlee van der Merwe, Sonja Herholdt, Elize Cawood, Rouel Beukes, Kevin Leo, Paul du Toit, Sylvaine Strike      1
Lisa Vicari, Dennis Mojen, Walid Al-Atiyat, Christina Hecke, Zoë Straub, Lisa Hagmeister, Hans-Jochen Wagner, André Eisermann, Ernst Stötzner      1
Piotr Cyrwus, Mikołaj Kubacki, Anna Radwan, Marian Dziędziel, Jan Nowicki, Juliusz Chrząstowski, Małgorzata Krzysica, Jacek Strama                 1
Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanana, Manish Chaudhary, Meghna Malik, Malkeet Rauni, Anita Shabdish, Chittaranjan Tripathy              1
Name: count, Length: 7679, dtype: int64
----------------------------------------
Value counts for column 'country':
country
United States                             2809
India                                      972
Unknown                                    829
United Kingdom                             418
Japan                                      243
                                          ...
Romania, Bulgaria, Hungary                   1
Uruguay, Guatemala                           1
France, Senegal, Belgium                     1
Mexico, United States, Spain, Colombia       1
United Arab Emirates, Jordan                 1
Name: count, Length: 749, dtype: int64
----------------------------------------
Value counts for column 'date_added':
date_added
January 1, 2020      109
November 1, 2019      89
March 1, 2018         75
December 31, 2019     74
October 1, 2018       71
                    ...
December 4, 2016       1
November 21, 2016      1
November 19, 2016      1
November 17, 2016      1
January 11, 2020       1
Name: count, Length: 1765, dtype: int64
----------------------------------------
Value counts for column 'release_year':
release_year
2018    1146
2017    1030
2019    1030
2020     953
2016     901
        ...
1959       1
1925       1
1961       1
1947       1
1966       1
Name: count, Length: 74, dtype: int64
----------------------------------------
Value counts for column 'rating':
rating
TV-MA       3205
TV-14       2157
TV-PG        861
R            799
PG-13        490
TV-Y7        333
TV-Y         306
PG           287
TV-G         220
NR            79
G             41
TV-Y7-FV       6
NC-17          3
UR             3
Name: count, dtype: int64
----------------------------------------
Value counts for column 'duration':
duration
1 Season     1791
2 Seasons     421
3 Seasons     198
90 min        152
94 min        146
             ...
16 min          1
186 min         1
193 min         1
189 min         1
191 min         1
Name: count, Length: 220, dtype: int64
----------------------------------------
Value counts for column 'listed_in':
listed_in
Dramas, International Movies                                   362
Documentaries                                                  359
Stand-Up Comedy                                                334
Comedies, Dramas, International Movies                         274
Dramas, Independent Movies, International Movies               252
                                                              ...
Crime TV Shows, International TV Shows, TV Sci-Fi & Fantasy      1
International TV Shows, TV Horror, TV Sci-Fi & Fantasy           1
Crime TV Shows, Kids' TV                                         1
Horror Movies, International Movies, Sci-Fi & Fantasy            1
Cult Movies, Dramas, Thrillers                                   1
Name: count, Length: 513, dtype: int64
----------------------------------------
Value counts for column 'description':
description
Paranormal activity at a lush, abandoned property alarms a group eager to redevelop the site, but the eerie events may not be as unearthly as they think.    4
Multiple women report their husbands as missing but when it appears they are looking for the same man, a police officer traces their cryptic connection.     3
Challenged to compose 100 songs before he can marry the girl he loves, a tortured but passionate singer-songwriter embarks on a poignant musical journey.    3
A surly septuagenarian gets another chance at her 20s after having her photo snapped at a studio that magically takes 50 years off her life.                 3
As a series of murders hit close to home, a video game designer with post-traumatic stress must confront her demons, or risk becoming their victim.          2
                                                                                                                                                            ..
Exhausted with his mother’s failed attempts at setting him up with women, Ican hires an ideal partner from a matchmaking app.                                1
Director Alfonso Cuarón reflects on the childhood memories, period details and creative choices that shaped his Academy Award-winning film "ROMA."           1
After spearheading an ill-fated bank robbery, a man must get his mentally challenged younger brother out of jail while eluding his own capture.              1
In this interactive special, Harold and George need your decision-making skills to stop Krupp from blowing their beloved treehouse to smithereens.           1
A scrappy but poor boy worms his way into a tycoon's dysfunctional family, while facing his fear of music and the truth about his past.                      1
Name: count, Length: 8758, dtype: int64
----------------------------------------

In [11]:
for col in df.columns:
    print(f"Length of Column '{col}'")
    print(len(df[col].value_counts()))
    print('-' * 40)

Length of Column 'show_id'
8790
----------------------------------------
Length of Column 'type'
2
----------------------------------------
Length of Column 'title'
8790
----------------------------------------
Length of Column 'director'
4527
----------------------------------------
Length of Column 'cast'
7679
----------------------------------------
Length of Column 'country'
749
----------------------------------------
Length of Column 'date_added'
1765
----------------------------------------
Length of Column 'release_year'
74
----------------------------------------
Length of Column 'rating'
14
----------------------------------------
Length of Column 'duration'
220
----------------------------------------
Length of Column 'listed_in'
513
----------------------------------------
Length of Column 'description'
8758
----------------------------------------

In [12]:
df.drop('show_id',axis=1, inplace=True)

In [13]:
engine = create_engine("mysql+pymysql://root:admin1234@localhost/netflix")
df.to_sql('table1', engine, if_exists="replace",index=False)

8790

In [14]:
%%sql
select * from table1 limit 5;

 * mysql+pymysql://root:***@localhost/netflix
5 rows affected.

[('Movie', 'Dick Johnson Is Dead', 'Kirsten Johnson', 'Unknown', 'United States', 'September 25, 2021', 2020, 'PG-13', '90 min', 'Documentaries', 'As her father nears the end of his life, filmmaker Kirsten Johnson stages his death in inventive and comical ways to help them both face the inevitable.'),
 ('TV Show', 'Blood & Water', 'Unknown', 'Ama Qamata, Khosi Ngema, Gail Mabalane, Thabang Molaba, Dillon Windvogel, Natasha Thahane, Arno Greeff, Xolile Tshabalala, Getmore Sithole, Cindy Mah ... (5 characters truncated) ... , Ryle De Morny, Greteli Fincham, Sello Maake Ka-Ncube, Odwa Gwanya, Mekaila Mathys, Sandi Schultz, Duane Williams, Shamilla Miller, Patrick Mofokeng', 'South Africa', 'September 24, 2021', 2021, 'TV-MA', '2 Seasons', 'International TV Shows, TV Dramas, TV Mysteries', 'After crossing paths at a party, a Cape Town teen sets out to prove whether a private-school swimming star is her sister who was abducted at birth.'),
 ('TV Show', 'Ganglands', 'Julien Leclercq', 'Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabiha Akkari, Sofia Lesaffre, Salim Kechiouche, Noureddine Farihi, Geert Van Rampelberg, Bakary Diombera', 'Unknown', 'September 24, 2021', 2021, 'TV-MA', '1 Season', 'Crime TV Shows, International TV Shows, TV Action & Adventure', 'To protect his family from a powerful drug lord, skilled thief Mehdi and his expert team of robbers are pulled into a violent and deadly turf war.'),
 ('TV Show', 'Jailbirds New Orleans', 'Unknown', 'Unknown', 'Unknown', 'September 24, 2021', 2021, 'TV-MA', '1 Season', 'Docuseries, Reality TV', 'Feuds, flirtations and toilet talk go down among the incarcerated women at the Orleans Justice Center in New Orleans on this gritty reality series.'),
 ('TV Show', 'Kota Factory', 'Unknown', 'Mayur More, Jitendra Kumar, Ranjan Raj, Alam Khan, Ahsaas Channa, Revathi Pillai, Urvi Singh, Arun Kumar', 'India', 'September 24, 2021', 2021, 'TV-MA', '2 Seasons', 'International TV Shows, Romantic TV Shows, TV Comedies', 'In a city of coaching centers known to train India’s finest collegiate minds, an earnest but unexceptional student and his friends navigate campus life.')]

In [15]:
df.head()

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,TV Show,Jailbirds New Orleans,Unknown,Unknown,Unknown,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

# 1.Total number of titles on Netflix

In [16]:
%%sql
select count(*) as total_titles from table1;

 * mysql+pymysql://root:***@localhost/netflix
1 rows affected.

[(8790,)]

# 2. Count of Movies vs TV Shows

In [17]:
%%sql
select type, count(*) as count
from table1 
group by type;

 * mysql+pymysql://root:***@localhost/netflix
2 rows affected.

[('Movie', 6126), ('TV Show', 2664)]

# 3. Percentage split of Movies vs TV Shows

In [18]:
%%sql
select type, round(count(*) * 100 / (select count(*) from netflix),2) as percentage
from table1
group by type;

 * mysql+pymysql://root:***@localhost/netflix
2 rows affected.

[('Movie', Decimal('69.69')), ('TV Show', Decimal('30.31'))]

# 4. Top 10 countries with most content

In [19]:
%%sql
select country, count(*) as total_titles
from table1
where country is not null and not country ='Unknown'
group by country
order by total_titles desc
limit 10;

 * mysql+pymysql://root:***@localhost/netflix
10 rows affected.

[('United States', 2809),
 ('India', 972),
 ('United Kingdom', 418),
 ('Japan', 243),
 ('South Korea', 199),
 ('Canada', 181),
 ('Spain', 145),
 ('France', 124),
 ('Mexico', 110),
 ('Egypt', 106)]

# 5. Number of titles produced by India

In [20]:
%%sql
select count(*) as ProducedByIndia
from table1
where country like '%India%';

 * mysql+pymysql://root:***@localhost/netflix
1 rows affected.

[(1046,)]

# 6. Countries producing more TV Shows than Movies

In [21]:
%%sql
select country from table1
group by country
having sum(type = 'TV Show') > sum(type='Movie')
limit 10;

 * mysql+pymysql://root:***@localhost/netflix
10 rows affected.

[('United Kingdom',),
 ('Australia',),
 ('Finland',),
 ('Japan',),
 ('Belgium',),
 ('South Korea',),
 ('United States, Singapore',),
 ('Russia',),
 (', South Korea',),
 ('Jordan',)]

# 7. Most common genres on Netflix

In [22]:
%%sql
select listed_in, count(*) as count
from table1
group by listed_in
order by count desc
limit 10;

 * mysql+pymysql://root:***@localhost/netflix
10 rows affected.

[('Dramas, International Movies', 362),
 ('Documentaries', 359),
 ('Stand-Up Comedy', 334),
 ('Comedies, Dramas, International Movies', 274),
 ('Dramas, Independent Movies, International Movies', 252),
 ("Kids' TV", 219),
 ('Children & Family Movies', 215),
 ('Children & Family Movies, Comedies', 201),
 ('Documentaries, International Movies', 186),
 ('Dramas, International Movies, Romantic Movies', 180)]

# 8. Most popular genre for Movies

In [23]:
%%sql
select listed_in, count(*) as movie_count
from table1
where type='Movie'
group by listed_in
order by movie_count desc
limit 5;

 * mysql+pymysql://root:***@localhost/netflix
5 rows affected.

[('Dramas, International Movies', 362),
 ('Documentaries', 359),
 ('Stand-Up Comedy', 334),
 ('Comedies, Dramas, International Movies', 274),
 ('Dramas, Independent Movies, International Movies', 252)]

# 9. Most popular genre for TV Shows

In [24]:
%%sql
select listed_in, count(*) as tv_show_count
from table1
where type='TV Show'
group by listed_in
order by tv_show_count desc
limit 5;

 * mysql+pymysql://root:***@localhost/netflix
5 rows affected.

[("Kids' TV", 219),
 ('International TV Shows, TV Dramas', 121),
 ('Crime TV Shows, International TV Shows, TV Dramas', 110),
 ("Kids' TV, TV Comedies", 97),
 ('Reality TV', 95)]

# 10. Number of titles released each year

In [25]:
%%sql
select release_year, count(*) as total
from table1
group by release_year
order by release_year desc;

 * mysql+pymysql://root:***@localhost/netflix
74 rows affected.

[(2021, 592),
 (2020, 953),
 (2019, 1030),
 (2018, 1146),
 (2017, 1030),
 (2016, 901),
 (2015, 555),
 (2014, 352),
 (2013, 286),
 (2012, 236),
 (2011, 185),
 (2010, 192),
 (2009, 152),
 (2008, 135),
 (2007, 88),
 (2006, 96),
 (2005, 80),
 (2004, 64),
 (2003, 59),
 (2002, 51),
 (2001, 45),
 (2000, 37),
 (1999, 39),
 (1998, 36),
 (1997, 38),
 (1996, 24),
 (1995, 25),
 (1994, 22),
 (1993, 28),
 (1992, 23),
 (1991, 17),
 (1990, 22),
 (1989, 16),
 (1988, 18),
 (1987, 8),
 (1986, 13),
 (1985, 10),
 (1984, 12),
 (1983, 11),
 (1982, 17),
 (1981, 13),
 (1980, 11),
 (1979, 11),
 (1978, 7),
 (1977, 7),
 (1976, 9),
 (1975, 7),
 (1974, 7),
 (1973, 10),
 (1972, 5),
 (1971, 5),
 (1970, 2),
 (1969, 2),
 (1968, 3),
 (1967, 5),
 (1966, 1),
 (1965, 2),
 (1964, 2),
 (1963, 2),
 (1962, 3),
 (1961, 1),
 (1960, 4),
 (1959, 1),
 (1958, 3),
 (1956, 2),
 (1955, 3),
 (1954, 2),
 (1947, 1),
 (1946, 2),
 (1945, 4),
 (1944, 3),
 (1943, 3),
 (1942, 2),
 (1925, 1)]

# 11. Year with highest number of releases

In [26]:
%%sql
SELECT release_year, COUNT(*) AS total
FROM table1
GROUP BY release_year
ORDER BY total desc
limit 5;

 * mysql+pymysql://root:***@localhost/netflix
5 rows affected.

[(2018, 1146), (2019, 1030), (2017, 1030), (2020, 953), (2016, 901)]

# 12. Titles added to Netflix each year

In [27]:
%%sql
select YEAR(STR_TO_DATE(date_added, '%M %d, %Y')) AS year_added,
       COUNT(*) AS total
FROM table1
WHERE date_added IS NOT NULL
GROUP BY year_added
ORDER BY year_added desc
limit 10;

 * mysql+pymysql://root:***@localhost/netflix
10 rows affected.

[(2021, 1498),
 (2020, 1879),
 (2019, 2016),
 (2018, 1648),
 (2017, 1185),
 (2016, 426),
 (2015, 82),
 (2014, 24),
 (2013, 11),
 (2012, 3)]

# 13. Average movie duration

In [28]:
%%sql
select AVG(CAST(SUBSTRING_INDEX(duration, ' ', 1) AS UNSIGNED)) AS avg_duration
from table1
where type='Movie';

 * mysql+pymysql://root:***@localhost/netflix
1 rows affected.

[(Decimal('99.5849'),)]

# 14. Longest movie on Netflix

In [29]:
%%sql
select title, duration from table1
where type = 'Movie'
order by CAST(SUBSTRING_INDEX(duration, ' ', 1) AS UNSIGNED) DESC
limit 1;

 * mysql+pymysql://root:***@localhost/netflix
1 rows affected.

[('Black Mirror: Bandersnatch', '312 min')]

# 15. TV Show with highest number of seasons

In [30]:
%%sql
select title, duration from table1 
where type = 'TV Show'
order by CAST(SUBSTRING_INDEX(duration, ' ', 1) AS UNSIGNED) DESC
limit 1;

 * mysql+pymysql://root:***@localhost/netflix
1 rows affected.

[("Grey's Anatomy", '17 Seasons')]

# 16. Count of titles by rating

In [31]:
%%sql
select rating, count(*) as total from table1
group by rating
order by total desc;

 * mysql+pymysql://root:***@localhost/netflix
14 rows affected.

[('TV-MA', 3205),
 ('TV-14', 2157),
 ('TV-PG', 861),
 ('R', 799),
 ('PG-13', 490),
 ('TV-Y7', 333),
 ('TV-Y', 306),
 ('PG', 287),
 ('TV-G', 220),
 ('NR', 79),
 ('G', 41),
 ('TV-Y7-FV', 6),
 ('NC-17', 3),
 ('UR', 3)]

# 17. Most common rating for Movies

In [32]:
%%sql
select rating, count(*) as total
from table1
where type = 'Movie'
group by rating
order by total desc
limit 1;

 * mysql+pymysql://root:***@localhost/netflix
1 rows affected.

[('TV-MA', 2062)]

# 18. Most common rating for TV Shows

In [33]:
%%sql
select rating, count(*) as total
from table1
where type = 'TV Show'
group by rating
order by total desc
limit 1;

 * mysql+pymysql://root:***@localhost/netflix
1 rows affected.

[('TV-MA', 1143)]

# 19. Director with most titles

In [34]:
%%sql
select director, count(*) as total_titles
from table1
where not director ='Unknown'
group by director
order by total_titles desc
limit 5;

 * mysql+pymysql://root:***@localhost/netflix
5 rows affected.

[('Rajiv Chilaka', 19),
 ('Raúl Campos, Jan Suter', 18),
 ('Marcus Raboy', 16),
 ('Suhas Kadav', 16),
 ('Jay Karas', 14)]

# 20. Directors who worked in both Movies and TV Shows

In [35]:
%%sql
select director from table1
where not director = 'Unknown'
group by director
having count(DISTINCT type) = 2
limit 5;

 * mysql+pymysql://root:***@localhost/netflix
5 rows affected.

[('Alessandro Angulo',),
 ('BB Sasore',),
 ('Billy Corben',),
 ('Brad Anderson',),
 ('Bunmi Ajakaiye',)]

# 21. Cumulative titles added over years

In [36]:
%%sql
WITH yearly_totals AS(
    select YEAR(STR_TO_DATE(date_added, '%M %d, %Y')) AS year_added, count(*) as total from table1
    where date_added IS NOT NULL
    group by year_added                                                                           
)

select year_added, SUM(total) OVER(ORDER BY year_added ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) as cumulative_titles
from yearly_totals
order by year_added;

 * mysql+pymysql://root:***@localhost/netflix
14 rows affected.

[(2008, Decimal('2')),
 (2009, Decimal('4')),
 (2010, Decimal('5')),
 (2011, Decimal('18')),
 (2012, Decimal('21')),
 (2013, Decimal('32')),
 (2014, Decimal('56')),
 (2015, Decimal('138')),
 (2016, Decimal('564')),
 (2017, Decimal('1749')),
 (2018, Decimal('3397')),
 (2019, Decimal('5413')),
 (2020, Decimal('7292')),
 (2021, Decimal('8790'))]

# 22. Top 5 years with maximum content growth

In [37]:
%%sql
select year_added, total
from (
    select 
        YEAR(STR_TO_DATE(date_added, '%M %d, %Y')) AS year_added,
        count(*) AS total
    from table1
    group by year_added
) AS yearly_totals
order by total DESC
limit 5;

 * mysql+pymysql://root:***@localhost/netflix
5 rows affected.

[(2019, 2016), (2020, 1879), (2018, 1648), (2021, 1498), (2017, 1185)]

# 23. Movie to TV Show ratio

In [38]:
%%sql
select sum(type='Movie') / sum(type = 'TV Show') AS movie_tv_ratio 
from table1;

 * mysql+pymysql://root:***@localhost/netflix
1 rows affected.

[(Decimal('2.2995'),)]

# 24. Countries focusing more on Movies

In [39]:
%%sql
select country from table1
group by country
having sum(type='Movie') > sum(type='TV Show')
limit 5;

 * mysql+pymysql://root:***@localhost/netflix
5 rows affected.

[('United States',),
 ('South Africa',),
 ('Unknown',),
 ('India',),
 ('United States, Ghana, Burkina Faso, United Kingdom, Germany, Ethiopia',)]

# 25. Countries focusing more on TV Shows

In [40]:
%%sql
select country from table1
group by country
having sum(type='Movie') <  sum(type='TV Show')
limit 5;

 * mysql+pymysql://root:***@localhost/netflix
5 rows affected.

[('United Kingdom',), ('Australia',), ('Finland',), ('Japan',), ('Belgium',)]

# 26. Titles with missing director information

In [41]:
%%sql
select count(*) from table1 
where director = 'Unknown';

 * mysql+pymysql://root:***@localhost/netflix
1 rows affected.

[(2621,)]

# 27. Titles with missing country

In [42]:
%%sql
select count(*) from table1
where country = 'Unknown';

 * mysql+pymysql://root:***@localhost/netflix
1 rows affected.

[(829,)]

# 28. Titles missing both director and cast

In [43]:
%%sql
select count(*) from table1
where country = 'Unknown' and director = 'Unknown'

 * mysql+pymysql://root:***@localhost/netflix
1 rows affected.

[(407,)]

# 29. Rank years by number of releases

In [44]:
%%sql
select release_year, count(*) as total, RANK() OVER(ORDER BY COUNT(*) desc) as year_rank
from table1
group by release_year
limit 10;

 * mysql+pymysql://root:***@localhost/netflix
10 rows affected.

[(2018, 1146, 1),
 (2019, 1030, 2),
 (2017, 1030, 2),
 (2020, 953, 4),
 (2016, 901, 5),
 (2021, 592, 6),
 (2015, 555, 7),
 (2014, 352, 8),
 (2013, 286, 9),
 (2012, 236, 10)]

# 30. Top 3 genres per year

In [45]:
%%sql
WITH ranked_categories AS (
    select 
        release_year,listed_in, count(*) as total,
        DENSE_RANK() OVER (PARTITION BY release_year ORDER BY COUNT(*) DESC) AS rnk
    from table1
    group by release_year, listed_in
)
select release_year, listed_in, total
from ranked_categories
where rnk <= 3;

 * mysql+pymysql://root:***@localhost/netflix
565 rows affected.

[(1925, 'TV Shows', 1),
 (1942, 'Classic Movies, Documentaries', 2),
 (1943, 'Documentaries', 2),
 (1943, 'Classic Movies, Documentaries', 1),
 (1944, 'Classic Movies, Documentaries', 3),
 (1945, 'Classic Movies, Documentaries', 3),
 (1945, 'TV Shows', 1),
 (1946, 'Classic Movies, Documentaries', 1),
 (1946, 'TV Shows', 1),
 (1947, 'Classic Movies, Documentaries', 1),
 (1954, 'Children & Family Movies, Classic Movies, Comedies', 1),
 (1954, 'Classic Movies, Dramas, International Movies', 1),
 (1955, 'Classic Movies, Comedies, Independent Movies', 2),
 (1955, 'Classic Movies, Dramas', 1),
 (1956, 'Classic Movies, Dramas, International Movies', 1),
 (1956, 'Action & Adventure, Classic Movies, Sci-Fi & Fantasy', 1),
 (1958, 'Classic Movies, Dramas, International Movies', 1),
 (1958, 'Classic Movies, Dramas', 1),
 (1958, 'Classic Movies, Comedies, Music & Musicals', 1),
 (1959, 'Dramas, International Movies', 1),
 (1960, 'Comedies, Dramas, International Movies', 1),
 (1960, 'Classic Movies, Dramas, Romantic Movies', 1),
 (1960, 'Action & Adventure, Dramas, International Movies', 1),
 (1960, 'Action & Adventure, Classic Movies, Comedies', 1),
 (1961, 'Action & Adventure, Classic Movies', 1),
 (1962, 'Comedies, Dramas, International Movies', 1),
 (1962, 'Classic Movies, Dramas, Romantic Movies', 1),
 (1962, 'Action & Adventure, Classic Movies, Dramas', 1),
 (1963, 'Action & Adventure, Classic Movies, Dramas', 1),
 (1963, 'Classic & Cult TV, TV Sci-Fi & Fantasy', 1),
 (1964, 'Classic Movies, Music & Musicals', 1),
 (1964, 'Classic Movies, Dramas, International Movies', 1),
 (1965, 'Classic Movies, Dramas, Romantic Movies', 1),
 (1965, 'Classic Movies, Dramas', 1),
 (1966, 'Dramas, International Movies, Music & Musicals', 1),
 (1967, 'Action & Adventure, Classic Movies, Dramas', 1),
 (1967, 'Classic Movies, Dramas', 1),
 (1967, 'Classic & Cult TV, TV Comedies', 1),
 (1967, 'Classic Movies, Dramas, International Movies', 1),
 (1967, 'Classic Movies, Dramas, Independent Movies', 1),
 (1968, 'Children & Family Movies, Classic Movies, Comedies', 1),
 (1968, 'Action & Adventure, Classic Movies, International Movies', 1),
 (1968, 'Classic Movies, Horror Movies, Thrillers', 1),
 (1969, 'Dramas, International Movies, Romantic Movies', 1),
 (1969, 'Classic Movies, Dramas', 1),
 (1970, 'Classic Movies, Dramas, International Movies', 1),
 (1970, 'Comedies, Cult Movies, International Movies', 1),
 (1971, 'Classic Movies, Dramas, International Movies', 1),
 (1971, 'Action & Adventure, Cult Movies, International Movies', 1),
 (1971, 'Classic Movies, Cult Movies, Dramas', 1),
 (1971, 'Classic Movies, Dramas, Music & Musicals', 1),
 (1971, 'Children & Family Movies, Classic Movies, Comedies', 1),
 (1972, 'Documentaries', 1),
 (1972, 'International TV Shows, TV Comedies', 1),
 (1972, 'Classic Movies, Comedies, Dramas', 1),
 (1972, 'International Movies, Romantic Movies', 1),
 (1972, 'Action & Adventure, Classic Movies, Dramas', 1),
 (1973, 'Action & Adventure, International Movies', 2),
 (1973, 'Action & Adventure, Classic Movies', 2),
 (1973, 'Comedies, Dramas, International Movies', 1),
 (1973, 'Classic Movies, Dramas, International Movies', 1),
 (1973, 'Children & Family Movies, Classic Movies', 1),
 (1973, 'Dramas, International Movies, Romantic Movies', 1),
 (1973, 'Documentaries, Music & Musicals', 1),
 (1973, 'Classic Movies, Dramas, Independent Movies', 1),
 (1974, 'British TV Shows, Classic & Cult TV, International TV Shows', 1),
 (1974, 'Comedies, International Movies, Music & Musicals', 1),
 (1974, 'Classic Movies, Comedies, Dramas', 1),
 (1974, 'Dramas, International Movies, Romantic Movies', 1),
 (1974, 'Comedies, Dramas, Independent Movies', 1),
 (1974, 'Classic Movies, Comedies, Sports Movies', 1),
 (1974, 'Cult Movies, Horror Movies, Independent Movies', 1),
 (1975, 'Classic Movies, Dramas, International Movies', 2),
 (1975, 'Action & Adventure, Classic Movies, Dramas', 1),
 (1975, 'Action & Adventure, Classic Movies, Comedies', 1),
 (1975, 'Action & Adventure, International Movies, Music & Musicals', 1),
 (1975, 'Classic Movies, Comedies, International Movies', 1),
 (1975, 'Action & Adventure, Dramas, International Movies', 1),
 (1976, 'Dramas, International Movies', 1),
 (1976, 'Action & Adventure, Classic Movies', 1),
 (1976, 'Comedies, International Movies', 1),
 (1976, 'Comedies, International Movies, Romantic Movies', 1),
 (1976, 'Classic Movies, Cult Movies, Horror Movies', 1),
 (1976, 'Action & Adventure, Comedies, Dramas', 1),
 (1976, 'Action & Adventure, Classic Movies, Cult Movies', 1),
 (1976, 'Action & Adventure, Classic Movies, Dramas', 1),
 (1976, 'Dramas, Music & Musicals', 1),
 (1977, 'Documentaries, International Movies', 1),
 (1977, 'Action & Adventure, Classic Movies, Dramas', 1),
 (1977, 'Action & Adventure, Classic Movies, Comedies', 1),
 (1977, 'British TV Shows, Classic & Cult TV, TV Comedies', 1),
 (1977, 'Children & Family Movies', 1),
 (1977, 'Dramas, Independent Movies, International Movies', 1),
 (1977, 'Cult Movies, Horror Movies', 1),
 (1978, 'Dramas, Horror Movies, Thrillers', 1),
 (1978, 'Action & Adventure, Dramas, International Movies', 1),
 (1978, 'Children & Family Movies', 1),
 (1978, 'Action & Adventure, International Movies', 1),
 (1978, 'Classic Movies, Comedies, Music & Musicals', 1),
 (1978, 'Action & Adventure, Cult Movies, International Movies', 1),
 (1978, 'Dramas, Independent Movies, International Movies', 1),
 (1979, 'Action & Adventure, Classic Movies, Cult Movies', 2),
 (1979, 'Documentaries, International Movies', 1),
 (1979, 'Classic Movies, Dramas, International Movies', 1),
 (1979, 'Comedies, Dramas, International Movies', 1),
 (1979, 'Classic Movies, Comedies, Cult Movies', 1),
 (1979, 'Action & Adventure, Anime Features, Classic Movies', 1),
 (1979, 'Stand-Up Comedy', 1),
 (1979, "Classic & Cult TV, Kids' TV, Spanish-Language TV Shows", 1),
 (1979, 'Classic Movies, Comedies, International Movies', 1),
 (1979, 'Dramas, Sports Movies', 1),
 (1980, 'Dramas, Romantic Movies', 1),
 (1980, 'Action & Adventure', 1),
 (1980, 'Documentaries, International Movies', 1),
 (1980, 'Action & Adventure, Dramas, International Movies', 1),
 (1980, 'Action & Adventure, International Movies, Sci-Fi & Fantasy', 1),
 (1980, 'Classic Movies, Comedies, Dramas', 1),
 (1980, 'Dramas', 1),
 (1980, 'Action & Adventure, Children & Family Movies, Comedies', 1),
 (1980, 'Classic Movies, Dramas, Sports Movies', 1),
 (1980, 'Action & Adventure, Comedies, International Movies', 1),
 (1980, 'Action & Adventure, International Movies', 1),
 (1981, 'Action & Adventure, Anime Features, International Movies', 1),
 (1981, 'Action & Adventure, Anime Features, Classic Movies', 1),
 (1981, 'Comedies, Romantic Movies', 1),
 (1981, 'Cult Movies, Dramas, Music & Musicals', 1),
 (1981, 'Comedies, Dramas, International Movies', 1),
 (1981, 'Comedies, International Movies, Romantic Movies', 1),
 (1981, 'Action & Adventure, Children & Family Movies, Classic Movies', 1),
 (1981, 'Action & Adventure, Dramas, International Movies', 1),
 (1981, 'Comedies, International Movies', 1),
 (1981, "Anime Series, Kids' TV", 1),
 (1981, 'Classic Movies, Comedies, Cult Movies', 1),
 (1981, 'Classic Movies, Cult Movies, Horror Movies', 1),
 (1981, 'Classic Movies, Dramas', 1),
 (1982, 'Dramas, Independent Movies, International Movies', 3),
 (1982, 'Action & Adventure, Classic Movies, Cult Movies', 1),
 (1982, 'Action & Adventure, Anime Features, International Movies', 1),
 (1982, 'Cult Movies, Dramas, International Movies', 1),
 (1982, 'Classic Movies, Dramas, Independent Movies', 1),
 (1982, 'Comedies, International Movies, Romantic Movies', 1),
 (1982, 'Comedies', 1),
 (1982, 'Action & Adventure, International Movies', 1),
 (1982, 'Comedies, Dramas, Independent Movies', 1),
 (1982, 'Action & Adventure, Cult Movies, International Movies', 1),
 (1982, 'Action & Adventure, Comedies, International Movies', 1),
 (1982, 'Dramas, Sports Movies', 1),
 (1982, 'Comedies, Cult Movies, Dramas', 1),
 (1982, 'Children & Family Movies', 1),
 (1982, 'Dramas, International Movies', 1),
 (1983, 'Dramas, Independent Movies, International Movies', 2),
 (1983, 'Action & Adventure, Horror Movies, Thrillers', 1),
 (1983, 'Comedies, Cult Movies', 1),
 (1983, 'Dramas, International Movies, Music & Musicals', 1),
 (1983, 'Stand-Up Comedy', 1),
 (1983, 'Action & Adventure, International Movies, Romantic Movies', 1),
 (1983, 'Action & Adventure, International Movies', 1),
 (1983, 'Dramas, International Movies, Romantic Movies', 1),
 (1983, 'Action & Adventure, Dramas, International Movies', 1),
 (1983, 'Dramas, International Movies', 1),
 (1984, 'Action & Adventure, Children & Family Movies, Classic Movies', 2),
 (1984, 'Comedies, Dramas, International Movies', 2),
 (1984, 'Classic Movies, Dramas', 1),
 (1984, 'Action & Adventure, Classic Movies, Cult Movies', 1),
 (1984, 'Action & Adventure, Dramas, International Movies', 1),
 (1984, 'Dramas, International Movies, Romantic Movies', 1),
 (1984, 'Action & Adventure, International Movies', 1),
 (1984, 'Comedies, International Movies, Romantic Movies', 1),
 (1984, 'Action & Adventure, Cult Movies', 1),
 (1984, 'Classic Movies, Dramas, Sports Movies', 1),
 (1985, 'Comedies, Cult Movies, International Movies', 2),
 (1985, 'Comedies, International Movies', 1),
 (1985, 'Action & Adventure, International Movies', 1),
 (1985, 'Horror Movies, International Movies, Thrillers', 1),
 (1985, 'Classic Movies, Dramas, International Movies', 1),
 (1985, 'Anime Series', 1),
 (1985, 'Dramas, Sports Movies', 1),
 (1985, 'Action & Adventure, Comedies, International Movies', 1),
 (1985, 'Comedies, Dramas, Independent Movies', 1),
 (1986, 'Action & Adventure, International Movies', 2),
 (1986, 'Dramas', 2),
 (1986, 'Action & Adventure, Children & Family Movies, Cult Movies', 1),
 (1986, 'Action & Adventure, Comedies', 1),
 (1986, 'Classic Movies, Comedies, Cult Movies', 1),
 (1986, 'Action & Adventure, Children & Family Movies, Dramas', 1),
 (1986, 'Anime Series', 1),
 (1986, 'Dramas, International Movies, Music & Musicals', 1),
 (1986, 'Children & Family Movies', 1),
 (1986, 'Action & Adventure, Classic Movies, Dramas', 1),
 (1986, 'TV Dramas', 1),
 (1987, 'Stand-Up Comedy', 2),
 (1987, 'Action & Adventure, Horror Movies, Thrillers', 1),
 (1987, 'Action & Adventure, Comedies, Dramas', 1),
 (1987, 'Dramas', 1),
 (1987, 'Action & Adventure, Dramas', 1),
 (1987, 'Classic Movies, Dramas, Music & Musicals', 1),
 (1987, 'Cult Movies, Horror Movies', 1),
 (1988, 'Dramas', 2),
 (1988, 'Action & Adventure, Classic Movies, Comedies', 1),
 (1988, 'Action & Adventure, Anime Features, International Movies', 1),
 (1988, 'Classic Movies, Dramas', 1),
 (1988, 'Comedies, Dramas, Independent Movies', 1),
 (1988, 'Action & Adventure, International Movies', 1),
 (1988, 'Docuseries, Reality TV', 1),
 (1988, 'Dramas, Sports Movies', 1),
 (1988, 'Cult Movies, Horror Movies', 1),
 (1988, 'TV Dramas', 1),
 (1988, 'Comedies, Cult Movies, Horror Movies', 1),
 (1988, 'Comedies, International Movies, Romantic Movies', 1),
 (1988, 'Dramas, International Movies', 1),
 (1988, 'Movies', 1),
 (1988, 'Comedies, Dramas', 1),
 (1988, 'Comedies, Cult Movies', 1),
 (1988, 'Documentaries, Music & Musicals', 1),
 (1989, 'Dramas', 2),
 (1989, 'Classic Movies, Comedies, Dramas', 1),
 (1989, 'Children & Family Movies, Dramas', 1),
 (1989, 'Action & Adventure, Sports Movies', 1),
 (1989, 'Children & Family Movies, Comedies', 1),
 (1989, 'Classic Movies, Dramas, International Movies', 1),
 (1989, 'Stand-Up Comedy', 1),
 (1989, 'Comedies', 1),
 (1989, 'Action & Adventure, Dramas, International Movies', 1),
 (1989, 'Dramas, International Movies', 1),
 (1989, 'Children & Family Movies', 1),
 (1989, 'Action & Adventure, Comedies, International Movies', 1),
 (1989, 'Action & Adventure, Children & Family Movies, Classic Movies', 1),
 (1989, 'Dramas, International Movies, Music & Musicals', 1),
 (1989, "Kids' TV", 1),
 (1990, 'Dramas', 2),
 (1990, 'Action & Adventure, Dramas, International Movies', 2),
 (1990, 'Comedies, Cult Movies', 1),
 (1990, 'Action & Adventure, Classic Movies, Dramas', 1),
 (1990, 'Action & Adventure', 1),
 (1990, 'Comedies, Dramas, International Movies', 1),
 (1990, 'Action & Adventure, Sci-Fi & Fantasy', 1),
 (1990, 'Dramas, International Movies', 1),
 (1990, 'Stand-Up Comedy', 1),
 (1990, 'Comedies, Dramas, Independent Movies', 1),
 (1990, 'Classic Movies, Dramas', 1),
 (1990, 'Docuseries', 1),
 (1990, 'Documentaries, Music & Musicals', 1),
 (1990, 'Action & Adventure, Comedies, International Movies', 1),
 (1990, 'Classic Movies, Cult Movies, Documentaries', 1),
 (1990, "Classic & Cult TV, Kids' TV, TV Comedies", 1),
 (1990, 'Dramas, Sports Movies', 1),
 (1990, 'Action & Adventure, Comedies', 1),
 (1990, 'Comedies, Cult Movies, Horror Movies', 1),
 (1990, 'Classic & Cult TV, Crime TV Shows, TV Dramas', 1),
 (1991, 'Stand-Up Comedy', 4),
 (1991, 'Classic Movies, Dramas, Independent Movies', 2),
 (1991, 'Comedies, Cult Movies, Music & Musicals', 1),
 (1991, 'Dramas', 1),
 (1991, 'Action & Adventure, Comedies', 1),
 (1991, 'Dramas, International Movies, Music & Musicals', 1),
 (1991, 'Dramas, Sports Movies', 1),
 (1991, 'Dramas, Thrillers', 1),
 (1991, 'Children & Family Movies', 1),
 (1991, 'TV Shows', 1),
 (1991, 'Comedies, Independent Movies, International Movies', 1),
 (1991, 'Children & Family Movies, Comedies', 1),
 (1991, 'Comedies', 1),
 (1992, 'Action & Adventure', 3),
 (1992, 'Stand-Up Comedy', 2),
 (1992, 'Action & Adventure, Dramas, International Movies', 2),
 (1992, 'TV Comedies', 1),
 (1992, 'Children & Family Movies, Comedies', 1),
 (1992, 'Horror Movies', 1),
 (1992, 'Dramas', 1),
 (1992, 'Comedies, International Movies, Sci-Fi & Fantasy', 1),
 (1992, 'Classic Movies, Dramas, Independent Movies', 1),
 (1992, "British TV Shows, Kids' TV, TV Comedies", 1),
 (1992, 'Classic Movies, Thrillers', 1),
 (1992, 'Comedies', 1),
 (1992, 'Cult Movies, Horror Movies', 1),
 (1992, 'Classic & Cult TV, TV Comedies', 1),
 (1992, 'Action & Adventure, Comedies, International Movies', 1),
 (1992, 'Classic Movies, Dramas, International Movies', 1),
 (1992, 'Classic Movies, Comedies, Romantic Movies', 1),
 (1992, 'Classic Movies, Independent Movies, Thrillers', 1),
 (1992, 'Classic Movies, Dramas', 1),
 (1993, 'Classic Movies, Dramas, Independent Movies', 2),
 (1993, 'Children & Family Movies, Comedies', 2),
 (1993, 'Action & Adventure, Dramas, International Movies', 2),
 (1993, 'Dramas, International Movies, Music & Musicals', 2),
 (1993, 'Dramas, Independent Movies, International Movies', 1),
 (1993, 'Action & Adventure', 1),
 (1993, 'Action & Adventure, Classic Movies', 1),
 (1993, 'Classic Movies, Dramas, International Movies', 1),
 (1993, "Kids' TV", 1),
 (1993, 'Reality TV', 1),
 (1993, 'Stand-Up Comedy', 1),
 (1993, 'TV Action & Adventure, TV Sci-Fi & Fantasy', 1),
 (1993, 'Dramas, Romantic Movies', 1),
 (1993, 'Dramas', 1),
 (1993, 'Children & Family Movies, Dramas', 1),
 (1993, 'Action & Adventure, Comedies, Independent Movies', 1),
 (1993, 'Classic Movies, Dramas, LGBTQ Movies', 1),
 (1993, 'Classic Movies, Dramas', 1),
 (1993, 'Children & Family Movies, Classic Movies, Dramas', 1),
 (1993, 'Thrillers', 1),
 (1993, 'TV Dramas', 1),
 (1993, 'Action & Adventure, International Movies', 1),
 (1993, 'Comedies, International Movies, Sci-Fi & Fantasy', 1),
 (1993, 'Dramas, Thrillers', 1),
 (1994, 'Dramas, International Movies', 2),
 (1994, 'Documentaries', 2),
 (1994, 'Action & Adventure', 2),
 (1994, "Kids' TV, TV Comedies", 1),
 (1994, 'Dramas, International Movies, Thrillers', 1),
 (1994, 'Action & Adventure, Dramas', 1),
 (1994, 'Comedies, Music & Musicals', 1),
 (1994, 'Children & Family Movies, Comedies, Dramas', 1),
 (1994, 'Action & Adventure, Sci-Fi & Fantasy', 1),
 (1994, 'Action & Adventure, Dramas, Sports Movies', 1),
 (1994, 'Action & Adventure, Comedies, Cult Movies', 1),
 (1994, 'Classic Movies, Dramas, International Movies', 1),
 (1994, 'Comedies, Dramas, International Movies', 1),
 (1994, 'TV Shows', 1),
 (1994, 'Classic Movies, Comedies, International Movies', 1),
 (1994, 'Action & Adventure, Comedies, International Movies', 1),
 (1994, 'Classic Movies, Cult Movies, Dramas', 1),
 (1994, 'Action & Adventure, Cult Movies, Sci-Fi & Fantasy', 1),
 (1994, 'Children & Family Movies, Comedies', 1),
 (1995, 'Action & Adventure, Comedies, International Movies', 2),
 (1995, 'Children & Family Movies, Dramas', 2),
 (1995, 'Dramas, International Movies, Romantic Movies', 1),
 (1995, 'Dramas, Independent Movies, Romantic Movies', 1),
 (1995, 'Comedies', 1),
 (1995, 'Thrillers', 1),
 (1995, 'Action & Adventure, Thrillers', 1),
 (1995, 'Action & Adventure, Sci-Fi & Fantasy', 1),
 (1995, 'Anime Series, International TV Shows', 1),
 (1995, 'Dramas, International Movies, Music & Musicals', 1),
 (1995, 'Action & Adventure, Comedies', 1),
 (1995, 'Action & Adventure, International Movies, Music & Musicals', 1),
 (1995, 'Action & Adventure', 1),
 (1995, 'Dramas, Romantic Movies', 1),
 (1995, 'Children & Family Movies, Comedies', 1),
 (1995, 'Comedies, Independent Movies, Romantic Movies', 1),
 (1995, 'Dramas, International Movies', 1),
 (1995, 'Dramas', 1),
 (1995, 'Comedies, Dramas, Romantic Movies', 1),
 (1995, 'Comedies, Cult Movies, LGBTQ Movies', 1),
 (1995, 'Comedies, Horror Movies, Sci-Fi & Fantasy', 1),
 (1995, 'Action & Adventure, Dramas, International Movies', 1),
 (1995, "Kids' TV", 1),
 (1996, 'Comedies, International Movies', 2),
 (1996, 'Comedies, Romantic Movies', 2),
 (1996, 'Action & Adventure', 2),
 (1996, 'Dramas, International Movies, Romantic Movies', 2),
 (1996, "Kids' TV", 2),
 (1996, 'Comedies, Cult Movies, Sci-Fi & Fantasy', 1),
 (1996, 'Comedies, Dramas, Romantic Movies', 1),
 (1996, 'Comedies, Dramas, International Movies', 1),
 (1996, 'Comedies, Cult Movies', 1),
 (1996, 'Action & Adventure, Sci-Fi & Fantasy', 1),
 (1996, 'Docuseries', 1),
 (1996, 'Comedies, Cult Movies, Sports Movies', 1),
 (1996, 'Dramas, Thrillers', 1),
 (1996, 'Dramas, Independent Movies', 1),
 (1996, 'Comedies, Dramas', 1),
 (1996, 'Horror Movies, Thrillers', 1),
 (1996, 'Comedies', 1),
 (1996, 'Thrillers', 1),
 (1996, 'Comedies, Cult Movies, Dramas', 1),
 (1997, 'Action & Adventure', 4),
 (1997, 'Dramas, Thrillers', 3),
 (1997, 'Comedies', 2),
 (1997, 'Comedies, Dramas, Independent Movies', 2),
 (1997, 'Thrillers', 2),
 (1997, 'Comedies, Romantic Movies', 2),
 (1997, "Kids' TV", 2),
 (1997, 'Action & Adventure, Comedies', 2),
 (1997, "Kids' TV, TV Comedies", 2),
 (1997, 'Action & Adventure, International Movies', 2),
 (1998, 'Comedies, Dramas, International Movies', 3),
 (1998, 'Dramas, International Movies', 2),
 (1998, 'Dramas', 2),
 (1998, 'Comedies, Sports Movies', 2),
 (1998, 'Comedies, International Movies, Romantic Movies', 1),
 (1998, 'Action & Adventure, Comedies', 1),
 (1998, 'Dramas, Romantic Movies, Sci-Fi & Fantasy', 1),
 (1998, 'Dramas, Music & Musicals, Romantic Movies', 1),
 (1998, 'Documentaries', 1),
 (1998, 'Dramas, Independent Movies, Thrillers', 1),
 (1998, 'TV Comedies, Teen TV Shows', 1),
 (1998, 'Comedies, Dramas, Independent Movies', 1),
 (1998, 'Children & Family Movies, Comedies', 1),
 (1998, 'Action & Adventure, Anime Features, International Movies', 1),
 (1998, 'Comedies, Documentaries', 1),
 (1998, 'Comedies', 1),
 (1998, 'Dramas, International Movies, Romantic Movies', 1),
 (1998, 'Stand-Up Comedy', 1),
 (1998, "Kids' TV, TV Thrillers", 1),
 (1998, 'Comedies, Cult Movies', 1),
 (1998, 'Comedies, Romantic Movies', 1),
 (1998, 'Thrillers', 1),
 (1998, 'Comedies, Cult Movies, Dramas', 1),
 (1998, 'Dramas, Independent Movies, LGBTQ Movies', 1),
 (1998, 'Documentaries, Music & Musicals', 1),
 (1998, 'Action & Adventure, Comedies, Independent Movies', 1),
 (1998, "Kids' TV", 1),
 (1998, 'Anime Series, International TV Shows', 1),
 (1998, 'Children & Family Movies', 1),
 (1998, 'Action & Adventure, Comedies, Sci-Fi & Fantasy', 1),

# 31. Average duration of movies per release year

In [46]:
%%sql
select release_year, AVG(CAST(SUBSTRING_INDEX(duration, ' ', 1) AS UNSIGNED)) AS avg_duration
from table1
where type='Movie'
group by release_year
order by release_year desc
limit 10;

 * mysql+pymysql://root:***@localhost/netflix
10 rows affected.

[(2021, Decimal('96.4440')),
 (2020, Decimal('92.1412')),
 (2019, Decimal('93.4660')),
 (2018, Decimal('96.1851')),
 (2017, Decimal('95.6118')),
 (2016, Decimal('95.3602')),
 (2015, Decimal('99.4747')),
 (2014, Decimal('100.2614')),
 (2013, Decimal('98.0489')),
 (2012, Decimal('100.7572'))]

# 32. Titles containing keyword "love"

In [47]:
%%sql
select title from table1 where description LIKE '%love%'
limit 5;

 * mysql+pymysql://root:***@localhost/netflix
5 rows affected.

[('Jeans',),
 ('Love on the Spectrum',),
 ('Minsara Kanavu',),
 ('Grown Ups',),
 ('Ankahi Kahaniya',)]

# 33. Oldest content available on Netflix

In [48]:
%%sql
select title, release_year from table1
order by release_year
limit 1;

 * mysql+pymysql://root:***@localhost/netflix
1 rows affected.

[('Pioneers: First Women Filmmakers*', 1925)]

# 34. Newest content available on Netflix

In [49]:
%%sql
select title, release_year from table1
order by release_year desc
limit 1;

 * mysql+pymysql://root:***@localhost/netflix
1 rows affected.

[('Blood & Water', 2021)]

# 35. Average number of titles added per year

In [50]:
%%sql
WITH yearly_totals AS(
    select YEAR(STR_TO_DATE(date_added, '%M %d, %Y')) as year,
    count(*) as total
    from table1
    group by year
)
select avg(total) as avg_titles_per_year from yearly_totals;

 * mysql+pymysql://root:***@localhost/netflix
1 rows affected.

[(Decimal('627.8571'),)]

# 36. Is Netflix shifting focus from Movies to TV Shows?

In [51]:
%%sql
select YEAR(STR_TO_DATE(date_added, '%M %d, %Y')) as year_added,
    sum(type='Movie') as movies,
    sum(type='TV Show') as tv_shows
from table1
where date_added is NOT NULL
group by year_added
order by year_added;

 * mysql+pymysql://root:***@localhost/netflix
14 rows affected.

[(2008, Decimal('1'), Decimal('1')),
 (2009, Decimal('2'), Decimal('0')),
 (2010, Decimal('1'), Decimal('0')),
 (2011, Decimal('13'), Decimal('0')),
 (2012, Decimal('3'), Decimal('0')),
 (2013, Decimal('6'), Decimal('5')),
 (2014, Decimal('19'), Decimal('5')),
 (2015, Decimal('56'), Decimal('26')),
 (2016, Decimal('251'), Decimal('175')),
 (2017, Decimal('836'), Decimal('349')),
 (2018, Decimal('1237'), Decimal('411')),
 (2019, Decimal('1424'), Decimal('592')),
 (2020, Decimal('1284'), Decimal('595')),
 (2021, Decimal('993'), Decimal('505'))]

# 37. Are international productions increasing? (Not US-based)

In [52]:
%%sql
select 
    YEAR(STR_TO_DATE(date_added, '%M %d, %Y')) AS year_added,
    count(*) AS international_titles
from table1
where country not like '%United States%'
  and date_added is not null
group by year_added
order by year_added;

 * mysql+pymysql://root:***@localhost/netflix
11 rows affected.

[(2009, 1),
 (2011, 1),
 (2013, 1),
 (2014, 2),
 (2015, 25),
 (2016, 225),
 (2017, 724),
 (2018, 1048),
 (2019, 1160),
 (2020, 1051),
 (2021, 871)]

# 38. What genres dominate different regions?

In [53]:
%%sql
WITH country_genre AS (
    select country, listed_in, count(*) AS total,
        RANK() OVER (PARTITION BY country ORDER BY COUNT(*) DESC) AS rnk
    from table1
    group by country, listed_in
)
select country, listed_in AS top_genre, total
from country_genre
where rnk = 1
limit 10;

 * mysql+pymysql://root:***@localhost/netflix
10 rows affected.

[(', France, Algeria', 'Dramas, Independent Movies, International Movies', 1),
 (', South Korea', 'International TV Shows, TV Dramas', 1),
 ('Argentina', 'Stand-Up Comedy', 8),
 ('Argentina, Brazil, France, Poland, Germany, Denmark', 'Dramas, International Movies, Thrillers', 1),
 ('Argentina, Chile', 'Dramas, Independent Movies, International Movies', 1),
 ('Argentina, Chile', 'Dramas, International Movies', 1),
 ('Argentina, Chile, Peru', 'Comedies, International Movies, Sports Movies', 1),
 ('Argentina, France', 'Dramas, Independent Movies, International Movies', 1),
 ('Argentina, France, United States, Germany, Qatar', 'Dramas, International Movies', 1),
 ('Argentina, Italy', 'Documentaries, International Movies', 1)]

# 39. Are newer movies longer or shorter?

In [54]:
%%sql
select release_year, AVG(CAST(SUBSTRING_INDEX(duration, ' ', 1) AS UNSIGNED)) AS avg_duration
from table1
where type='Movie'
group by release_year
order by release_year desc
limit 10;

 * mysql+pymysql://root:***@localhost/netflix
10 rows affected.

[(2021, Decimal('96.4440')),
 (2020, Decimal('92.1412')),
 (2019, Decimal('93.4660')),
 (2018, Decimal('96.1851')),
 (2017, Decimal('95.6118')),
 (2016, Decimal('95.3602')),
 (2015, Decimal('99.4747')),
 (2014, Decimal('100.2614')),
 (2013, Decimal('98.0489')),
 (2012, Decimal('100.7572'))]

# 40. Is Netflix investing more in multi-season shows?

In [55]:
%%sql
select 
    release_year, avg(CAST(SUBSTRING_INDEX(duration, ' ', 1) AS UNSIGNED)) AS avg_seasons
from table1
where type = 'TV Show'
group by release_year
order by release_year desc
limit 10;

 * mysql+pymysql://root:***@localhost/netflix
10 rows affected.

[(2021, Decimal('1.7175')),
 (2020, Decimal('1.7110')),
 (2019, Decimal('1.8690')),
 (2018, Decimal('1.6755')),
 (2017, Decimal('1.7887')),
 (2016, Decimal('1.6091')),
 (2015, Decimal('1.6604')),
 (2014, Decimal('1.5682')),
 (2013, Decimal('1.6557')),
 (2012, Decimal('1.8254'))]

# 41. What ratings dominate family-friendly content?

In [56]:
%%sql
select rating, count(*) as total_titles from table1
where rating IN ('G', 'PG', 'TV-Y', 'TV-Y7')
group by rating
order by total_titles desc;

 * mysql+pymysql://root:***@localhost/netflix
4 rows affected.

[('TV-Y7', 333), ('TV-Y', 306), ('PG', 287), ('G', 41)]

# 42. Which countries offer the most diverse content?

In [57]:
%%sql
select country, count(distinct listed_in) AS genre_diversity from table1
where not country = 'Unknown'
group by country
order by genre_diversity desc
limit 10;

 * mysql+pymysql://root:***@localhost/netflix
10 rows affected.

[('United States', 310),
 ('United Kingdom', 99),
 ('India', 90),
 ('Canada', 85),
 ('Japan', 55),
 ('Australia', 54),
 ('United Kingdom, United States', 48),
 ('Spain', 46),
 ('France', 44),
 ('United States, Canada', 39)]